export const HI_RES_CARD_WIDTH = 733
export const HI_RES_CARD_HEIGHT = 1024

export const SMALL_CARD_WIDTH = 245
export const SMALL_CARD_HEIGHT = 342

export const GRID_CARD_ASPECT_RATIO = SMALL_CARD_WIDTH / SMALL_CARD_HEIGHT
export const SCREEN_CARD_ASPECT_RATIO = HI_RES_CARD_WIDTH / HI_RES_CARD_HEIGHT

