export declare type Rarity =
  | 'custom'
  | 'amazing rare'
  | 'common'
  | 'radiant rare'
  | 'rare holo'
  | 'rare holo galaxy'
  | 'rare holo v'
  | 'rare holo vmax'
  | 'rare holo vstar'
  | 'rare rainbow'
  | 'rare rainbow alt'
  | 'rare secret'
  | 'rare ultra'
  | 'uncommon';
