export declare type Subtype =
  | 'basic'
  | 'basic v'
  | 'basic v fusion strike'
  | 'basic v rapid strike'
  | 'basic v single strike'
  | 'item'
  | 'pokémon tool'
  | 'stadium'
  | 'stage 1'
  | 'stage 2'
  | 'stage 2 rapid strike'
  | 'supporter'
  | 'vmax'
  | 'vmax rapid strike'
  | 'vmax single strike'
  | 'vstar';
