export const cardRarityMapper = {
  "ACE SPEC Rare": "rare holo v",
  "Amazing Rare": "amazing rare",
  "Classic Collection": "common",
  "Common": "common",
  "Double rare": "rare holo",
  "Full Art Trainer": "full art trainer",
  "Holo Rare": "holo rare",
  "Holo Rare V": "holo rare v",
  "Holo Rare VMAX": "holo rare vmax",
  "Holo Rare VSTAR": "holo rare vstar",
  "Hyper rare": "hyper rare",
  "Illustration rare": "illustration rare",
  "LEGEND": "legend",
  "None": "none",
  "Radiant Rare": "radiant rare",
  "Rare": "rare",
  "Rare Holo": "rare holo",
  "Rare Holo LV.X": "rare holo lv.x",
  "Rare PRIME": "rare prime",
  "Secret Rare": "rare secret",
  "Shiny Ultra Rare": "rare ultra",
  "Shiny rare": "shiny rare",
  "Shiny rare V": "rare holo v",
  "Shiny rare VMAX": "rare holo vmax",
  "Special illustration rare": "special illustration rare",
  "Ultra Rare": "rare ultra",
  "Uncommon": "uncommon"
};