enum Series {
  Base = 'Base',
  Gym = 'Gym',
  Neo = 'Neo',
  Other = 'Other',
  ECard = 'E-Card',
  EX = 'EX',
  NP = 'NP',
  POP = 'POP',
  TrainerKits = 'Trainer Kits',
  Promos = 'Promos',
  DP = 'Diamond & Pearl',
  Platinum = 'Platinum',
  HGSS = 'HeartGold & SoulSilver',
  BW = 'Black & White',
  XY = 'XY',
  SM = 'Sun & Moon',
  SWSH = 'Sword & Shield',
  SV = 'Scarlet & Violet',
}