export enum Series {
  ScarletAndViolet = 'sv',
  SwordAndShield = 'swsh',
  SunAndMoon = 'sm',
  XY = 'xy',
  BlackAndWhite = 'bw',
  Platinum = 'pl',
  DiamondAndPearl = 'dp',
  HeartGoldAndSoulSilver = 'hgss',
  Neo = 'neo',
  Base = 'base',
  CallOfLegends = 'col',
  ECard = 'ecard',
  EX = 'ex',
  Gym = 'gym',
  LegendaryCollection = 'lc',
  McDonaldsCollection = 'mc',
  Miscellaneous = 'misc',
  POP = 'pop',
  TrainerKits = 'tk',
}